#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
Import('env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
rootlibs = env['ROOTLIBS']

debug = False

# force debug mode for this package only
env1  = env.Clone()

ccflags = env1['CCFLAGS'];
if ('-O3' in ccflags): ccflags.remove('-O3');

for f in ccflags:
    if (f == '-g'): ccflags.append(['-g','-O0'])
env1['CCFLAGS'] = ccflags

helper = stntuple_helper(env1,debug);

dict_skip_list = []
if (os.getenv("STNTUPLE_MC_GEN") == None): 
    dict_skip_list.append("TStnPhotosAnaModule_linkdef.h");

helper.handle_dictionaries(".hh",dict_skip_list);

list_of_cc_files =  Glob('*.cc', strings=True);
skip_list        = []
if (os.getenv("STNTUPLE_MC_GEN") == None): 
    skip_list.append("TStnPhotosAnaModule.cc");

stntuple_libs = [];
libs          = ['libcovid19_sim'] + [ rootlibs] ;

helper.build_libs(list_of_cc_files, skip_list,libs);

# print "tmpdir:"+env['TMP_LIB_DIR']
